[package]
name = "factor"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.33.3", default-features = false, features = ["default_fonts", "wgpu"] }
egui-snarl = "0.9.0"
meval = "0.2.0"
wgpu = "27"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
